# Generated by Django 5.1.5 on 2025-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=50)),
                ('company_id', models.IntegerField()),
            ],
        ),
    ]
