services:
  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/fleetms
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - fleetms-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    command: npm run dev
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - fleetms-network

  mongo:
    image: mongo:latest
    container_name: fleetms-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - fleetms-network

volumes:
  db_data:

networks:
  fleetms-network:
