name: Deploy on prod

on:
    push:
        branches:
        - main

    workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/kosssst/repos/fleetms
          git pull origin main
          sudo docker compose -f docker-compose-prod.yml up -d --build --force-recreate
